### ISSUE TITLE
Empty timesheet throws index out of range error

### ISSUE THREAD

**Issue by brandon-dp** [CaptainCuddleCube/TimeWriggler#2]
Empty timesheet in the Google Sheet causes an error for TimeWriggler.
```
(venv) brandon@brandon-XPS-13-9360:~/dataprophet/TimeWriggler$ python ./timewriggler.py 
Updating the time entries...
Thumbing your Toggl timesheets into google sheet format...
Traceback (most recent call last):
  File "./timewriggler.py", line 80, in <module>
    db.get_latest_time_entries(g_api.last_entered_date), args.round_up
  File "/home/brandon/dataprophet/TimeWriggler/tw_lib/google_api.py", line 109, in last_entered_date
    return current_timesheets[-1][0]
IndexError: list index out of range
```
Adding an entry resolves the issue.

**Comment by CaptainCuddleCube** [comment]
Pull, this was fixed.
